# Generated by Django 5.0.6 on 2024-06-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Выберите изображение",
                null=True,
                upload_to="blog/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
