# Generated by Django 5.0.6 on 2024-06-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="viewed",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
