# Generated by Django 5.0.6 on 2024-06-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_blog_viewed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
